### ISSUE TITLE
\n in register names break jasper.per

### ISSUE THREAD

**Issue by gshippee** [casper-astro/mlib_devel#18]
They need to be stripped off before generating the peripherals file, otherwise they break the yams encoding

**Comment by jack-h** [comment]
a) OMG, someone using github issues!
b) I think they probably break things further downstream, too, because register names end up being used all over the place for FPGA memory maps. I think the "fix" I will implement it just to have simulink flag these as errors, unless they are at the end of the name, in which case they will be silently stripped off.

Thanks for raising the issue

**Comment by jack-h** [comment]
in casper-astro-soak-test
