### ISSUE TITLE
ROACH gpio blocks don't cause error in ROACH2 design

### ISSUE THREAD

**Issue by amartens** [casper-astro/mlib_devel#7]

**Comment by jack-h** [comment]
ROACH2 headed towards deprecation. Won't Fix.
JASPER will dispense with platform descriptors in GPIO block names

**Comment by jack-h** [comment]
Reopening -- this leads to really irritating subtle errors.

**Comment by bjbford** [comment]
@jack-h what is this, is this similar what #26 was?

**Comment by jack-h** [comment]
Similar but different. In the original / ROACH2 flow, you do have to specify the platform. But, if you get it wrong, probably nothing will error out until right at the end. I.e., using a gpio block configured for ROACH:GPIO rather than ROACH2:GPIO will fail if compiling for ROACH2, but will not give any helpful indication about why.

One of the following should probably happen --
1. Error if the wrong platform is selected
2. Dispense with the platform specifier all together, as in #26 .

Probably doing something to verify the platform in the gpio yellow block class drc method is the easiest way to go -- https://github.com/casper-astro/mlib_devel/blob/roach2/xps_library/%40xps_gpio/drc.m

**Comment by jack-h** [comment]
Let's be honest, this isn't getting fixed.
